int a = 3;
int b = 11;
int c = 7;
int d = 5;
int e = 2;
int max = a;
if (a > max ) max = a;
if (b > max ) max = b;
if (c > max ) max = c;
if (d > max ) max = d;
if (e > max ) max = e;
Console.Write( max );